GET http://localhost:3000/songs.json
###
POST http://localhost:3000/songs.json
content-type: application/json

{
      "input_title": "song_1",
      "input_album": "album_1",
      "input_artist": "artist_1",
      "input_year": "year_1"

}
###
GET http://localhost:3000/songs/4.json
###
PATCH http://localhost:3000/songs/4.json
content-type: application/json

{

"input_title": "My latest song",
"input_album": "My newest Album",
"input_artist": "I'm the artist",
"input_year": "2021"


}
###
DELETE http://localhost:3000/songs/4.json
